server:
  name: "project-user"
  addr: "127.0.0.1:8080"
zap:
  debugFileName: "..\\logs\\debug\\project-debug.log"
  infoFileName: "..\\logs\\info\\project-info.log"
  warnFileName: "..\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "www.dzhxka.com"
  port: 5600
  Password: ""
  DB: 0
grpc:
  etcdAddr: "127.0.0.1:8881"
  addr: "127.0.0.1:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: Chulianpzj12345
  host: "www.dzhxka.com"
  port: 5000
  db: Myproject
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: msproject
  refreshSecret: ms_project
jaeger:
  endpoints: "http://localhost:14268/api/traces"